name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build apache image
      run: docker build ./apache --file Dockerfile --tag kompolom/bedrok-docker:apache-$(date +%s)
